# Generated by Django 4.2.5 on 2023-09-23 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('E', 'Easy'), ('M', 'Moderate'), ('H', 'Hard')], default='M', max_length=1)),
                ('distance', models.FloatField()),
                ('national_park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.national_park')),
            ],
        ),
    ]
